name: Go
env:
  EB_PACKAGE_S3_BUCKET_NAME = "alex-k-test-githubactions"
  EB_APPLICATION_NAME       = "myGoApp"
  EB_ENVIRONMENT_NAME       = "myGoApp-env"
  DEPOY_PACKAGE_NAME        = "go-app-${{ githab.sha }}.zip"
  AWS_REGION_NAME           = "us-west-2"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my_ci_pipeline:
  runs-on: ubuntu-latest
    steps:
      - name: clone our rep
      - uses: actions/checkout@v1
    
      - name: create zip file
      - run: zip -r ${{ env:DEPOY_PACKAGE_NAME }} ./ -x *.git* 
    
      - name: Configure AWS credetials
      - uses: aws-actions/configure-aws-credentials@v1
       with:   
             aws-access-key-id     = ${{ secrets.MY_AWS_ACCESS_KEY }}
             aws-access-secret-key = ${{ secrets.MY_AWS_SECRET_KEY }}
              aws-region            = ${{ env.AWS_REGION_NAME }}
            
      - name: Copy our package to S3
     - run: aws s3 cp ${{ env:DEPOY_PACKAGE_NAME }} s3://{{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
    
     - name: Print message
     - run: echo "CI Pipeline finish succesfully"
